Mvc/Controllers/TiresController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Models;
using Services.Interfaces;

namespace Mvc.Controllers
{
    public class TiresController : BaseController<Tire, ICrudServiceAsync<Tire>>
    {
        public TiresController(ICrudServiceAsync<Tire> service) : base(service)
        {
        }

        public async Task<IActionResult> Index(TireSeason? season) {
            var tires = await Service.ReadAsync();
            //string.Join(", ", users.Select(x => x.Login));
            
            if(season.HasValue)
                tires = tires.Where(x => x.Season.Equals(season));
            
            return View(tires);
        }
        
        public IActionResult Add() {
            return View(new Tire());
        }
        
        [HttpPost]
        public async Task<IActionResult> Add(Tire tire) 
        {
            if(!ModelState.IsValid) {
                return View(tire);
            }

            var users = await Service.ReadAsync();
            if(users.Any(x => x.Producer == tire.Producer))
            {
                ModelState.AddModelError(nameof(tire.Producer), "Producer already exists!");
                return View(tire);
            }

            await Service.CreateAsync(tire);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id) {
            if(!id.HasValue)
                return BadRequest();

            var item = await Service.ReadAsync(id.Value);
            if(item == null)
                return NotFound();

            return View(item);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, Tire tire) {
            if(!ModelState.IsValid) {
                return View(tire);
            }
            
            var tires = await Service.ReadAsync();
            if(tires.Where(x => x.Id != id).Any(x => x.Producer == tire.Producer))
            {
                //return BadRequest(ModelState);
                ModelState.AddModelError(nameof(tire.Producer), "Producer already exist");
                return View(tire);
            }
            
            await Service.UpdateAsync(id, tire);

            return RedirectToAction(nameof(Index));
        }
        
        public async Task<string> Search(string id, int limit = int.MaxValue) {
            // if(id == null)
            //     return await Index();

            var users = await Service.ReadAsync();
            return string.Join(", ", users.Take(limit).Select(x => x.Producer.Name).Where(x => x.Contains(id)));
        }
    }
}

Mvc/Controllers/UsersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models;
using Services.Interfaces;

namespace Mvc.Controllers
{
    [Authorize(Roles = nameof(Roles.Admin))]
    public class UsersController : BaseController<User, IUsersServiceAsync>
    {
        public UsersController(IUsersServiceAsync service) : base(service)
        {
        }

        [Authorize(Roles = nameof(Roles.Read))]
        public async Task<IActionResult> Index(string search, Roles? roles) {
            var users = await Service.FindAsync(search, roles);

            return View(users);
        }

        


        [Authorize(Roles = nameof(Roles.Create))]
            public IActionResult Add() {
            return View(new User());
        }

        [HttpPost]
        [Authorize(Roles = nameof(Roles.Create))]
        public async Task<IActionResult> Add(User user) {
            if(!ModelState.IsValid) {
                return View(user);
            }

            var users = await Service.ReadAsync();
            if(users.Any(x => x.Login == user.Login))
            {
                ModelState.AddModelError(nameof(user.Login), "Login already exists!");
                return View(user);
            }

            await Service.CreateAsync(user);
            return RedirectToAction(nameof(Index));
        }


        [Authorize(Roles = nameof(Roles.Update))]
            public async Task<IActionResult> Edit(int? id) {
            if(!id.HasValue)
                return BadRequest();

            var item = await Service.ReadAsync(id.Value);
            if(item == null)
                return NotFound();

            return View(item);
        }

        [HttpPost]
        [Authorize(Roles = nameof(Roles.Update))]
        public async Task<IActionResult> Edit(int id, User user) {
            if(!ModelState.IsValid) {
                return View(user);
            }

            var users = await Service.ReadAsync();
            if(users.Where(x => x.Id != id).Any(x => x.Login == user.Login))
            {
                //return BadRequest(ModelState);
                ModelState.AddModelError(nameof(user.Login), "Login already exists!");
                return View(user);
            }

            await Service.UpdateAsync(id, user);

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = nameof(Roles.Read))]
        public async Task<string> Search(string id, int limit = int.MaxValue) {
            // if(id == null)
            //     return await Index();

            var users = await Service.ReadAsync();
            return string.Join(", ", users.Take(limit).Select(x => x.Login).Where(x => x.Contains(id)));
        }
    }
}

Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Oponeo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Oponeo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Tires" asp-action="Index">Opony</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Mvc/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Oponeo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Oponeo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>